/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'djmittens' at '6/6/15 12:50 PM' with Gradle 2.4
 *
 * @author djmittens, @date 6/6/15 12:50 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
